spring:
#  mvc:
#    static-path-pattern: /res/**
#  web:
#    resources: 
#      static-locations: classpath:/static/img
  mvc:
    hiddenmethod:
      filter:
        enabled: true
          